version: "2"

networks:
  default:
    external:
      name: prodnetwork

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

services:
  gitlab:
    image: gitlab/gitlab-ce:10.4.3-ce.0
    container_name: gitlab
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
         external_url 'https://gitlab.example.com'
    environment:
      - VIRTUAL_HOST=gitlab.example.com
      - VIRTUAL_PORT=80
    ports:
      - "80"
      - "443"
      - "1000:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - /docker-volumes/gitlab/config:/etc/gitlab
      - /docker-volumes/gitlab/logs:/var/log/gitlab
      - /docker-volumes/gitlab/data:/var/opt/gitlab
