version: "2"

networks:
  default:
    external:
      name: prodnetwork

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

services:
  gitlab:
    image: gitlab/gitlab-ce:9.1.4-ce.0
    container_name: gitlab
    restart: always
    environment:
      - VIRTUAL_HOST=gitlab.example.com
      - VIRTUAL_PORT=80
      #GITLAB_OMNIBUS_CONFIG: |
        # external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "80"
      - "443"
      - "22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - /docker-volumes/gitlab/config:/etc/gitlab
      - /docker-volumes/gitlab/logs:/var/log/gitlab
      - /docker-volumes/gitlab/data:/var/opt/gitlab
